services:
  frontend:
    image: frontend
    container_name: frontend
    build: ./frontend
    env_file:
      - .env
    ports:
      - ${FRONTEND_HOST_PORT}:${FRONTEND_CONTAINER_PORT}
    depends_on:
      - backend

  backend:
    image: backend
    container_name: backend
    build: ./backend
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - ./backend/logs:/backend/logs
    ports:
      - ${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}

  mongodb:
    image: mongo:latest
    container_name: mongodb
    env_file:
      - .env
    ports:
      - ${DATABASE_HOST_PORT}:${DATABASE_CONTAINER_PORT}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db:/data/db
    command: --quiet --logpath /dev/null

volumes:
  db: